# Usar una imagen base de Node.js con Alpine para reducir el tamaño de la imagen
FROM node:alpine

# Establecer el directorio de trabajo en el contenedor
WORKDIR /usr/app

# Copiar el archivo package.json y package-lock.json (si existe) al directorio de trabajo
COPY package.json ./
COPY package-lock.json ./

# Instalar las dependencias del proyecto
RUN npm install

# Copiar el resto de los archivos del proyecto al directorio de trabajo
COPY ./ ./

# Añadir bash si es necesario para ejecutar scripts o comandos adicionales
RUN apk add --no-cache bash

# Asegurarse de que el script de entorno (si existe) tenga permisos de ejecución
RUN chmod +x ./env.sh

# Comando para iniciar la aplicación Vite.js
# Asegúrate de que el comando npm start esté configurado para iniciar Vite.js
# Si tu comando de inicio es diferente, reemplázalo aquí
CMD ["npm", "run", "dev"]
